/*******************************************************************************
 * @file momentum_can_dbc.c
 * @brief Auto-generated CAN message definitions from DBC file.
 *******************************************************************************
 */

/** Includes. *****************************************************************/

#include "momentum_can_dbc.h"

/** Public variables. *********************************************************/

const can_message_t dbc_messages[] = {
    {
        .name = "state",
        .message_id = 257,
        .id_mask = 0xFFFFFFFF,
        .dlc = 1,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 1,
        .signals =
            {
                {
                    .name = "system_state",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "barometric",
        .message_id = 258,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "pressure",
                    .start_bit = 0,
                    .bit_length = 32,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.00566f,
                    .offset = 30000.0f,
                    .min_value = 30000.0f,
                    .max_value = 24339514.8897f,
                },
                {
                    .name = "temperature",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0019074f,
                    .offset = -40.0f,
                    .min_value = -40.0f,
                    .max_value = 85.001459f,
                },
                {
                    .name = "barometric_state",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "gps1",
        .message_id = 259,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 2,
        .signals =
            {
                {
                    .name = "latitude",
                    .start_bit = 0,
                    .bit_length = 32,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 4.1909516e-08f,
                    .offset = -90.0f,
                    .min_value = -90.0f,
                    .max_value = 90.0000005692792f,
                },
                {
                    .name = "longitude",
                    .start_bit = 32,
                    .bit_length = 32,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 8.3819032e-08f,
                    .offset = -180.0f,
                    .min_value = -180.0f,
                    .max_value = 180.000001138558f,
                },
            },
    },
    {
        .name = "gps2",
        .message_id = 260,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 5,
        .signals =
            {
                {
                    .name = "speed",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.01f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 655.35f,
                },
                {
                    .name = "course",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.01f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 655.35f,
                },
                {
                    .name = "position_fix",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "satellite_count",
                    .start_bit = 40,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "hdop",
                    .start_bit = 48,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.01f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 655.35f,
                },
            },
    },
    {
        .name = "gps3",
        .message_id = 261,
        .id_mask = 0xFFFFFFFF,
        .dlc = 7,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "altitude",
                    .start_bit = 0,
                    .bit_length = 32,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.01f,
                    .offset = -150.0f,
                    .min_value = -150.0f,
                    .max_value = 42949522.95f,
                },
                {
                    .name = "geoid_separation",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.01f,
                    .offset = 0.0f,
                    .min_value = -327.68f,
                    .max_value = 327.67f,
                },
                {
                    .name = "gps_state",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
            },
    },
    {
        .name = "imu1",
        .message_id = 262,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "quaternion_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 3.05185e-05f,
                    .offset = -1.0f,
                    .min_value = -1.0f,
                    .max_value = 1.0000298975f,
                },
                {
                    .name = "quaternion_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 3.05185e-05f,
                    .offset = -1.0f,
                    .min_value = -1.0f,
                    .max_value = 1.0000298975f,
                },
                {
                    .name = "quaternion_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 3.05185e-05f,
                    .offset = -1.0f,
                    .min_value = -1.0f,
                    .max_value = 1.0000298975f,
                },
                {
                    .name = "quaternion_w",
                    .start_bit = 48,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 3.05185e-05f,
                    .offset = -1.0f,
                    .min_value = -1.0f,
                    .max_value = 1.0000298975f,
                },
            },
    },
    {
        .name = "imu2",
        .message_id = 263,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "gyro_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0610359f,
                    .offset = -2000.0f,
                    .min_value = -2000.0f,
                    .max_value = 1999.9877065f,
                },
                {
                    .name = "gyro_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0610359f,
                    .offset = -2000.0f,
                    .min_value = -2000.0f,
                    .max_value = 1999.9877065f,
                },
                {
                    .name = "gyro_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0610359f,
                    .offset = -2000.0f,
                    .min_value = -2000.0f,
                    .max_value = 1999.9877065f,
                },
            },
    },
    {
        .name = "imu3",
        .message_id = 264,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "accel_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0047889f,
                    .offset = -156.9f,
                    .min_value = -156.9f,
                    .max_value = 156.9405615f,
                },
                {
                    .name = "accel_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0047889f,
                    .offset = -156.9f,
                    .min_value = -156.9f,
                    .max_value = 156.9405615f,
                },
                {
                    .name = "accel_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0047889f,
                    .offset = -156.9f,
                    .min_value = -156.9f,
                    .max_value = 156.9405615f,
                },
            },
    },
    {
        .name = "imu4",
        .message_id = 265,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "lin_accel_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0047889f,
                    .offset = -156.9f,
                    .min_value = -156.9f,
                    .max_value = 156.9405615f,
                },
                {
                    .name = "lin_accel_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0047889f,
                    .offset = -156.9f,
                    .min_value = -156.9f,
                    .max_value = 156.9405615f,
                },
                {
                    .name = "lin_accel_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0047889f,
                    .offset = -156.9f,
                    .min_value = -156.9f,
                    .max_value = 156.9405615f,
                },
            },
    },
    {
        .name = "imu5",
        .message_id = 272,
        .id_mask = 0xFFFFFFFF,
        .dlc = 6,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 3,
        .signals =
            {
                {
                    .name = "gravity_x",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0002994f,
                    .offset = -9.81f,
                    .min_value = -9.81f,
                    .max_value = 9.811179f,
                },
                {
                    .name = "gravity_y",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0002994f,
                    .offset = -9.81f,
                    .min_value = -9.81f,
                    .max_value = 9.811179f,
                },
                {
                    .name = "gravity_z",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 0.0002994f,
                    .offset = -9.81f,
                    .min_value = -9.81f,
                    .max_value = 9.811179f,
                },
            },
    },
    {
        .name = "command_a",
        .message_id = 513,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 4,
        .signals =
            {
                {
                    .name = "command_u16_0",
                    .start_bit = 0,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "command_u16_1",
                    .start_bit = 16,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "command_u16_2",
                    .start_bit = 32,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
                {
                    .name = "command_u16_3",
                    .start_bit = 48,
                    .bit_length = 16,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 65535.0f,
                },
            },
    },
    {
        .name = "rtc",
        .message_id = 600,
        .id_mask = 0xFFFFFFFF,
        .dlc = 8,
        .rx_handler = 0,
        .tx_handler = 0,
        .signal_count = 8,
        .signals =
            {
                {
                    .name = "rtc_state",
                    .start_bit = 0,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 255.0f,
                },
                {
                    .name = "rtc_year",
                    .start_bit = 8,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 2000.0f,
                    .min_value = 2000.0f,
                    .max_value = 2099.0f,
                },
                {
                    .name = "rtc_month",
                    .start_bit = 16,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 12.0f,
                },
                {
                    .name = "rtc_day",
                    .start_bit = 24,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 31.0f,
                },
                {
                    .name = "rtc_weekday",
                    .start_bit = 32,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 1.0f,
                    .max_value = 7.0f,
                },
                {
                    .name = "rtc_hour",
                    .start_bit = 40,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 23.0f,
                },
                {
                    .name = "rtc_minute",
                    .start_bit = 48,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 59.0f,
                },
                {
                    .name = "rtc_second",
                    .start_bit = 56,
                    .bit_length = 8,
                    .byte_order = CAN_BIG_ENDIAN,
                    .scale = 1.0f,
                    .offset = 0.0f,
                    .min_value = 0.0f,
                    .max_value = 59.0f,
                },
            },
    },
};

const int dbc_message_count = sizeof(dbc_messages) / sizeof(dbc_messages[0]);
